# This file specifies the parameter settings for running snakemake on a cluster
"__default__" :
  "time" : "48:00:00"
  "mem" : 8G
  "n" : 1
"align_probe_bowtie" :
  "n" : 8
"simulate_reads" :
  "mem" : 1G
"build_blat_index" :
  "mem" : 4G
"run_wessim" :
  "mem" : 1G
